package com.example.demo;

public enum APIActionName {
  SERVICE_ACCOUNT_PROCESSING_API_ACTION_A,
  USER_ACCOUNT_PROCESSING_API_ACTION_A,
  SERVICE_ACCOUNT_PROCESSING_API_ACTION_B,
  USER_ACCOUNT_PROCESSING_API_ACTION_B,
  SERVICE_ACCOUNT_PROCESSING_API_ACTION_C,
  USER_ACCOUNT_PROCESSING_API_ACTION_C,


  SERVICE_ACCOUNT_TRANSACTION_API_ACTION_A,
  USER_ACCOUNT_TRANSACTION_API_ACTION_A,
  SERVICE_ACCOUNT_TRANSACTION_API_ACTION_B,
  USER_ACCOUNT_TRANSACTION_API_ACTION_B,
  SERVICE_ACCOUNT_TRANSACTION_API_ACTION_C,
  USER_ACCOUNT_TRANSACTION_API_ACTION_C

}
